AkachaRestaurant/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve

urlpatterns = [
    path('hidden/', admin.site.urls),
    path('', include('hotelmanagement.urls')),
    path("stock/", include("StockManagerApp.urls")),
    path("employee/",include("EmployeeManagement.urls")),
    path("Email/", include("EmailApp.urls")),
]
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve,{
    'document_root':settings.MEDIA_ROOT,
})]

EmailApp/urls.py
from django.urls import path
from .views import activate

urlpatterns = [
    path('activate/<uidb64>/<token>/', activate, name='activate'),
]

hotelmanagement/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import datetime
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.db.models import Sum
from cloudinary.models import CloudinaryField
from django.utils import timezone


# Create your models here.
class User_type(models.Model):
    id = models.AutoField(primary_key=True)
    user_type = models.CharField(max_length=50)

    def __str__(self):
        return self.user_type


class CustomUser(AbstractUser):
    # objects = models.Manager()
    id = models.AutoField(primary_key=True)
    profile = CloudinaryField("image")
    # profile = models.ImageField(upload_to="profiles/", default='profiles/default_profile.jpg')
    user_type = models.ForeignKey(User_type, on_delete=models.SET_NULL, null=True, default=None)
    is_active = models.BooleanField(default=True)
    customer_profit = models.DecimalField(decimal_places = 2, max_digits = 12, default=0.00)
    reset_password_token = models.CharField(max_length=255, blank=True, null=True)
    reset_password_expiration = models.DateTimeField(blank=True, null=True)

    def update_customer_profit(instance):
        order = instance
        total_profit = Order.objects.filter(order_receiver=order).aggregate(Sum('menu_items__item_profit'))[
                           'menu_items__item_profit__sum'] or 0
        order.customer_profit = total_profit
        order.save()
    def __str__(self):
        return self.username

class Restaurant(models.Model):
    objects = models.Manager()
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    contact = models.CharField(max_length=255)
    rating = models.DecimalField(max_digits=3, decimal_places=2, default = 0.0)
    description = models.TextField()
    def __str__(self):
        return self.name


class Table(models.Model):
    objects = models.Manager()
    id = models.AutoField(primary_key=True)
    # restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    table_number = models.CharField(max_length=10)
    capacity = models.PositiveIntegerField()
    def __str__(self):
        return self.table_number


class MenuCategory(models.Model):
    objects = models.Manager()
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name

class Cupon(models.Model):
    id = models.AutoField(primary_key=True)
    customer = models.ForeignKey(CustomUser, on_delete = models.CASCADE)
    ammount = models.DecimalField(max_digits = 7, decimal_places = 2)
    menu_item = models.ForeignKey('MenuItem', on_delete = models.CASCADE, null=True)
    used = models.BooleanField(default = False)
    def __str__(self):
        return self.ammount

class MenuItem(models.Model):
    # objects = models.Manager()
    id = models.AutoField(primary_key=True)
    category = models.ForeignKey(MenuCategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(decimal_places = 2, max_digits = 12)
    average_rating = models.DecimalField(max_digits=3, decimal_places=2, default=0.0)
    ingredient_cost = models.DecimalField(decimal_places = 2, max_digits = 12, default = 0.0)
    item_profit = models.DecimalField(decimal_places = 2, max_digits = 12, default = 0.0)
    orders_number = models.IntegerField(default = 0)
    def __str__(self):
        return self.name
    # image_url = models.URLField(blank=True, null=True)

    def save(self, *args, **kwargs):
        self.item_profit = self.price - self.ingredient_cost
        super(MenuItem, self).save(*args, **kwargs)

    def update_cost(instance):
        menu_item = instance
        total_cost = Ingredient.objects.filter(menu_item=menu_item).aggregate(Sum('price'))['price__sum'] or 0
        menu_item.ingredient_cost = total_cost
        menu_item.save()

    def update_orders_number(instance):
        menu_item = instance
        total_number = Order.objects.filter(menu_items=menu_item).count()
        menu_item.orders_number = total_number
        menu_item.save()


class MenuItemRating(models.Model):
    objects = models.Manager()
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default=None)  # Link the rating to a user
    menu_item = models.ForeignKey(MenuItem, on_delete=models.CASCADE, default=None)
    rating = models.DecimalField(decimal_places=1, max_digits=2, default = 0.0)
    comment = models.TextField(max_length=200, default="No comment")
    def __str__(self):
        return self.rating


class MenuImage(models.Model):
    objects = models.Manager()
    id = models.AutoField(primary_key=True)
    image = CloudinaryField("image")
#     image = models.ImageField(upload_to="menus/")
    menu_item = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    is_primary = models.BooleanField(default=False)


class Reservation(models.Model):
    objects = models.Manager()
    id = models.AutoField(primary_key=True)
    guest_name = models.CharField(max_length=255)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    table = models.ForeignKey(Table, on_delete=models.CASCADE)
    reservation_date = models.DateTimeField()
    party_size = models.PositiveIntegerField()


class Order(models.Model):
    objects = models.Manager()
    id = models.AutoField(primary_key=True)
    # restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    table = models.ForeignKey(Table, on_delete=models.CASCADE)
    # menu_items = models.ManyToManyField(MenuItem, through='OrderItem')
    menu_items = models.ForeignKey(MenuItem, on_delete=models.CASCADE, null=True)
    ordered_time = models.DateTimeField(auto_now = True)
    start_processing_time = models.DateTimeField(null=True, blank=True)
    received_time = models.DateTimeField(null=True, blank=True)
    order_processor = models.ForeignKey(CustomUser, related_name="processor", on_delete=models.DO_NOTHING, null=True)
    order_receiver = models.ForeignKey(CustomUser, on_delete=models.DO_NOTHING, null=True)
    send = models.BooleanField(default=False)
    latitude = models.DecimalField(max_digits = 18, decimal_places = 15, default=-6.216848786038759)
    longitude = models.DecimalField(max_digits = 18, decimal_places = 15, default=35.810966491699226)
    def __str__(self):
        return self.order_receiver


class OrderItem(models.Model):
    objects = models.Manager()
    id = models.AutoField(primary_key=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    menu_item = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()


class Review(models.Model):
    objects = models.Manager()
    id = models.AutoField(primary_key=True)
    guest_name = models.CharField(max_length=255)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    rating = models.DecimalField(max_digits=3, decimal_places=2, default = 0.0)
    comment = models.TextField()
    date = models.DateTimeField()


class Ingredient(models.Model):
    objects = models.Manager()
    id = models.AutoField(primary_key=True)
    menu_item = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    ingredient_name = models.CharField(max_length=50)
    measured_in = models.CharField(max_length=50)
    quantity = models.FloatField()
    price = models.DecimalField(decimal_places = 2, max_digits = 12)
    def __str__(self):
        return self.ingredient_name


class Employee(models.Model):
    objects = models.Manager()
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    address = models.TextField()
    role = models.CharField(max_length=255)
    salary = models.DecimalField(max_digits=10, decimal_places=2, default = 0.0)


class Payment(models.Model):
    objects = models.Manager()
    id = models.AutoField(primary_key=True)
    reservation = models.ForeignKey(Reservation, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default = 0.0)
    payment_date = models.DateTimeField()
    payment_method = models.CharField(max_length=255)


class Messages(models.Model):
    MESSAGE_TYPE = (
        ("Authorization", "Authorization"),
        ("Request", "Request"),
        ("Denial", "Denial"),
        ("Information", "Information"),
        ("Unknown", "Unknown")
    )

    USER_CATEGORY = (
        ("CEO", "CEO"),
        ("storekeeper", "Storekeeper"),
        ("chef", "Chef"),
        ("Waiter", "Waiter"),
        ("customer", "Customer"),
        ("None", "None")
    )

    sender = models.ForeignKey(to=CustomUser, on_delete=models.CASCADE, related_name="message_sender")
    receiver_category = models.ForeignKey(User_type, on_delete=models.CASCADE, null=True)
    # receiver = models.ForeignKey(to=CustomUser, on_delete=models.CASCADE, related_name="message_receiver")
    # receiver_category = models.CharField(choices=USER_CATEGORY, max_length=255, default=USER_CATEGORY[5])
    time_sent = models.DateTimeField(auto_now=True)
    time_opened = models.DateTimeField(null=True, blank=True)
    opened = models.BooleanField(default=False)
    message = models.TextField()
    message_type = models.CharField(choices=MESSAGE_TYPE, max_length=255, default=MESSAGE_TYPE[3])
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.message}"


@receiver(post_save, sender=Ingredient)
@receiver(post_delete, sender=Ingredient)
def update_menu_item(sender, instance, **kwargs):
    instance.menu_item.update_cost()


@receiver(post_save, sender=Order)
def update_menu_item(sender, instance, **kwargs):
    instance.order_receiver.update_customer_profit()


@receiver(post_save, sender=Order)

templates/Chef/base.html
{% extends 'links.html' %}
{% block links %}

          {% include 'Chef/side_bar.html'%}
          
{% endblock links %}

templates/Chef/home.html
{% extends 'Chef/base.html' %}
{% block content%}
    
      <div class="content-wrapper">
        <div class="page-header">
          <h3 class="page-title"><span class="page-title-icon bg-gradient-primary text-white me-2"><i class="mdi mdi-home"></i></span> Dashboard</h3>
          <nav aria-label="breadcrumb">
            <ul class="breadcrumb">
              <li class="breadcrumb-item active" aria-current="page">
                <span></span>Overview <i class="mdi mdi-alert-circle-outline icon-sm text-primary align-middle"></i>
              </li>
            </ul>
          </nav>
        </div>
        <div class="row">
          <div class="col-md-4 stretch-card grid-margin">
            <div class="card bg-gradient-danger card-img-holder text-white">
              <div class="card-body">
                <img src="../static/assets/images/dashboard/circle.svg" class="card-img-absolute" alt="circle-image" />
                <h4 class="font-weight-normal mb-3">Weekly Sales <i class="mdi mdi-chart-line mdi-24px float-right"></i></h4>
                <h2 class="mb-5">$ 15,0000</h2>
                <h6 class="card-text">Increased by 60%</h6>
              </div>
            </div>
          </div>
          <div class="col-md-4 stretch-card grid-margin">
            <div class="card bg-gradient-info card-img-holder text-white">
              <div class="card-body">
                <img src="../static/assets/images/dashboard/circle.svg" class="card-img-absolute" alt="circle-image" />
                <h4 class="font-weight-normal mb-3">Weekly Orders <i class="mdi mdi-bookmark-outline mdi-24px float-right"></i></h4>
                <h2 class="mb-5">45,6334</h2>
                <h6 class="card-text">Decreased by 10%</h6>
              </div>
            </div>
          </div>
          <div class="col-md-4 stretch-card grid-margin">
            <div class="card bg-gradient-success card-img-holder text-white">
              <div class="card-body">
                <img src="../static/assets/images/dashboard/circle.svg" class="card-img-absolute" alt="circle-image" />
                <h4 class="font-weight-normal mb-3">Visitors Online <i class="mdi mdi-diamond mdi-24px float-right"></i></h4>
                <h2 class="mb-5">95,5741</h2>
                <h6 class="card-text">Increased by 5%</h6>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
      <!-- partial:partials/_footer.html -->
      
      <!-- partial -->
    
{% endblock%}

templates/Chef/manage_ingredients.html
{% extends 'Chef/base.html' %}

{% block content %}
<div class="col-lg-12 grid-margin stretch-card" style="margin: 5px;">
    <div class="card">
      <div class="">
<h4>Ingredients management</h4>
        <div class="modal fade" id="add" tabindex="-1" role="dialog" aria-labelledby="updateModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="updateModalLabel">Add ingredient</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <!-- Add a form for updating the menu -->
                  <form method="post" enctype="multipart/form-data" action="{% url 'add_ingredient'%}">
                    {% csrf_token %}
                    <br>
                    <div class="form-group">
                      <select class="form-control" name="menu_id" id="id_category">
                          <option value="">Select</option>
                          {%for menuitem in menu_items%}
                          <option value="{{menuitem.id}}">{{menuitem.name}}</option>
                          {%endfor%}
                      </select>
                    </div>
                    <div class="form-group">
                      <input class="form-control" type="text" name="ingredient_name" placeholder="Ingredient name">
                    </div>
                    <div class="form-group">
                      <input class="form-control" type="text" name="measure" placeholder="Measuring scale">
                    </div>
                    <div class="form-group">
                      <input class="form-control" type="floatformat" name="quantity" placeholder="Number of unit scale">
                    </div>
                    <div class="form-group">
                      <input class="form-control" type="floatformat" name="price" placeholder="Price of unit scale">
                    </div>
                      <!-- This will render the form fields for updating the menu -->
                    <button type="submit" class="btn btn-primary">Add</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
          <h4><a href="#" class="add-button btn btn-success" data-toggle="modal" data-target="#add">Add ingredients</a></h4>
  

        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Menu Item</th>
                <th>Ingredient Name</th>
                <th>Measured In</th>
                <th>Quantity</th>
                <th>Price</th>
                <th colspan="2">Actions</th>
              </tr>
            </thead>
            <tbody>
              {% for ingredient in ingredients %}
                <tr>
                  <td>{{ingredient.menu_item.name}}</td>
                  <td>{{ingredient.ingredient_name}}</td>
                  <td>{{ingredient.measured_in}}</td>
                  <td>{{ingredient.quantity}}</td>
                  <td>{{ingredient.price}}</td>

                  <div class="modal fade" id="updateModal{{ ingredient.id }}" tabindex="-1" role="dialog" aria-labelledby="updateModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="updateModalLabel">Update {{ingredient.ingredient_name}}</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                          <!-- Add a form for updating the image -->
                          <form method="post" enctype="multipart/form-data" action="{% url 'edit_ingredient' ingredient.id%}">
                            {% csrf_token %}
                    <br>
                    <div class="form-group">
                      <select class="form-control" name="menu_id" id="id_category">
                          <option value="">Select</option>
                          {%for menuitem in menu_items%}
                          <option value="{{menuitem.id}}" {% if menuitem.id == ingredient.menu_item.id %} selected {% endif %}>{{menuitem.name}}</option>
                          {%endfor%}
                      </select>
                    </div>
                    <div class="form-group">
                      <input class="form-control" type="text" name="ingredient_name" value="{{ingredient.ingredient_name}}">
                    </div>
                    <div class="form-group">
                      <input class="form-control" type="text" name="measure" value="{{ingredient.measured_in}}">
                    </div>
                    <div class="form-group">
                      <input class="form-control" type="floatformat" name="quantity" value="{{ingredient.quantity}}">
                    </div>
                    <div class="form-group">
                      <input class="form-control" type="floatformat" name="price" value="{{ingredient.price}}">
                    </div>
                      <!-- This will render the form fields for updating the menu -->
                    <button type="submit" class="btn btn-primary">Add</button>
                  </form>
                        </div>
                      </div>
                    </div>
                  </div>
        
                  <!-- Modal for Delete Confirmation -->
                  <div class="modal fade" id="deleteModal{{ ingredient.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="deleteModalLabel">Confirm Delete {{ingredient.ingredient_name}}</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                          <p>Are you sure you want to delete this menu item?</p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                          <a class="btn btn-danger" href="{% url 'delete_ingredient' ingredient.id %}">Delete</a>
                        </div>
                      </div>
                    </div>
                  </div>
                    <td><button class="update-button btn btn-primary" data-toggle="modal" data-target="#updateModal{{ ingredient.id }}">Update</button></td>
                    <td><button class="delete-button btn btn-danger" data-toggle="modal" data-target="#deleteModal{{ ingredient.id }}">Delete</button></td>
        

                </tr>

              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/Chef/manage_menu_image.html
{% extends 'Chef/base.html' %}

{% block content %}
<div class="col-lg-12 grid-margin stretch-card" style="margin: 5px;">
    <div class="card">
      <div class="">

<h4>Menu Image Mangement</h4>

        <div class="modal fade" id="add" tabindex="-1" role="dialog" aria-labelledby="updateModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="updateModalLabel">Add Menu Image</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <!-- Add a form for updating the menu -->
                <form method="post" enctype="multipart/form-data" action="{% url 'add_menu_image'%}">
                  {% csrf_token %}
                  <br>
                  <div class="form-group">
                    <select class="form-control form-control-lg" name="menu_id" id="id_category">
                        <option value="">Select</option>
                        {%for menuitem in menuitems%}
                        <option value="{{menuitem.id}}">{{menuitem.name}}</option>
                        {%endfor%}
                    </select>
                  </div>
                  <div class="form-group">
                    <h5 style="text-align: center;">Add Item Image</h5>
                    <input type="file" class="form-control form-control-lg" id="exampleInputUsername1" name='image'>
                  </div>
                    <!-- This will render the form fields for updating the menu -->
                  <button type="submit" class="btn btn-primary">Add</button>
                </form>
              </div>
            </div>
          </div>
        </div>
        <h4><a href="#" class="add-button btn btn-success" data-toggle="modal" data-target="#add">Add Menu image</a></h4>


        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Menu Category</th>
                <th>Menu Item</th>
                <th>Menu Image</th>
                <th colspan="2">Actions</th>
              </tr>
            </thead>
            <tbody>
              {% for image in images %}
                <tr>
                  <td>{{image.menu_item.category.name}}</td>
                  <td>{{image.menu_item.name}}</td>
                  <td>
                    {%if image.image %}
                    <a href="{{image.image.url}}">
                        <img src="{{ image.image.url }}" style="width: 100px; height: 150px; border-radius: 0px;" />
                    </a>
                    {%endif%}
                </td>

                          
                              
            <!-- Modal for Update Confirmation -->
                  <div class="modal fade" id="updateModal{{ image.id }}" tabindex="-1" role="dialog" aria-labelledby="updateModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="updateModalLabel">Update {{image.name}}</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                          <!-- Add a form for updating the image -->
                          <form method="post" enctype="multipart/form-data" action="{% url 'edit_menu_image' image.id%}">
                            {% csrf_token %}
                            <br>
                            <div class="form-group">
                              <select class="form-control form-control-lg" name="menu_id">
                                  <option value="">Select</option>
                                  {%for menuitem in menuitems%}
                                  <option value="{{menuitem.id}}" {% if image.menu_item.id == menuitem.id %} selected {% endif %}>{{menuitem.name}}</option>
                                  {%endfor%}
                              </select>
                            </div>
                            <div class="form-group">
                              {% if image.image %}
                              <h5><img width="120px" src="{{image.image.url}}" alt="image"></h5>
                              {% endif %}
                              <h5 style="text-align: center;">edit Item Image</h5>
                              <input type="file" class="form-control form-control-lg" id="exampleInputUsername1" name='image'>
                            </div>
                              <!-- This will render the form fields for updating the menu -->
                            <button type="submit" class="btn btn-primary">Add</button>
                          </form>
                        </div>
                      </div>
                    </div>
                  </div>

                  <!-- Modal for Delete Confirmation -->
                  <div class="modal fade" id="deleteModal{{ image.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="deleteModalLabel">Confirm Delete {{image.name}}</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                          <p>Are you sure you want to delete this menu item?</p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                          <a class="btn btn-danger" href="{% url 'delete_menu_image' image.id %}">Delete</a>
                        </div>
                      </div>
                    </div>
                  </div>
                  <td><button class="update-button btn btn-primary" data-toggle="modal" data-target="#updateModal{{ image.id }}">Update</button></td>
                  <td><button class="delete-button btn btn-danger" data-toggle="modal" data-target="#deleteModal{{ image.id }}">Delete</button></td>


                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}

templates/Chef/side_bar.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'mystyle.css' %}" />
    <title>Homepage</title>
  </head>
  <body>
    <nav class="sidebar sidebar-offcanvas" id="sidebar">
      <ul class="nav">
        <li class="nav-item nav-profile">
          <a href="{% url 'home'%}"  class="nav-link">
            <div class="nav-profile-image">
              {% if user.profile %}
                <img src="{{user.profile.url}}" alt="profile" />
              {% endif %}
              <span class="login-status online"></span>
              <!-- change to offline or busy as needed -->
            </div>
            <div class="nav-profile-text d-flex flex-column">
              <span class="font-weight-bold mb-2">{{user.username}}</span>
              <span class="text-secondary text-small">{{user.user_type}}</span>
            </div>
            <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link"  href="{% url 'home'%}">
            <span class="menu-title">Dashboard</span>
            <i class="mdi mdi-home menu-icon"></i>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link "    id="manage-menu-category" href="{%url 'manage_menu_category'%}">
            <span class="menu-title">Manage menu categories</span>
            <i class="mdi mdi-contacts menu-icon"></i>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link "   id="manage-menu-item" href="{% url 'manage_menu_item'%}">
            <span class="menu-title">Manage Menu Items</span>
            <i class="mdi mdi-contacts menu-icon"></i>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link "   id="manage-menu-image" href="{% url 'manage_menu_image'%}">
            <span class="menu-title">Manage Menu Images</span>
            <i class="mdi mdi-contacts menu-icon"></i>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link "   id="food-item-list" href="{% url 'food_item_list' %}">
            <span class="menu-title">Manage Stocks</span>
            <i class="mdi mdi mdi-stocking menu-icon"></i>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link "   id="manage-ingredient" href="{% url 'manage_ingredient' %}">
            <span class="menu-title">Manage Ingredients</span>
            <i class="mdi mdi mdi-stocking menu-icon"></i>
          </a>
        </li>
      </ul>
    </nav>
  </body>
</html>